const test = `vJrwpWtwJgWrhcsFMMfFFhFp
jqHRNqRjqzjGDLGLrsFMfFZSrLrFZsSL
PmmdzqPrVvPwwTWBwg
wMqvLMZHhHMvwLHjbvcjnnSBnvTQFn
ttgJtRGJQctTZtZT
CrZsJsPPZsGzwwsLwLmpwMDw`;

const input = `NLBLfrNNLvqwbMfDqSjSzzSJjjggcdVs
lTRGPPZnRRHszcsZdSsccZ
CFTTFtFHTtCtDDzrmBtrBD
BJldgBWnRgWNWtllSlWShMcLcVSvVjbVVVvDVVVL
HFGFwqQPQGwHrTFpwmThMbDDVcVmLvvshj
HrpHrGPZZCQrfqlNdtMlzfMltlgn
hQLhBtBtQNQjBjNLvtLjzLJpWbjJdppSwjpCCplllJdj
FGFsmccSPTVPfVVHpJJgwlJwwWJWpCmR
sFPfPFHZTHScnzBttqzvQzqZ
MNTGMTnGWvTwwwnZhNZnWDPPdSjqsSPWjmBCSBWS
RJrtVfRlLrfHgblHJVBjqqFmjCdBJjDmJdSD
tgRftftRcRLftrpHpflHlctVwNNvZNcTwZnznQzwTzmhQwQh
sQPpQpQhnlNsJpJSQphHcZffLfgLHSfHVHHFZZ
zBCvrrWzTwqzcbtbqCbrCCwWLMfVVmmHVfqHFHFgGHLZGmVG
rvvjBzTjrwQRcpjNsRss
RrnNWJJNrplbLJBBWWZstVpmtZftptfmfsMM
GHjnwndzGcqjGgqtfMsvfsMmMvZZ
cQgwHTPjPwGwjdHHTjwccQBDLlWNrLJLNrnWrBRBlS
BBBQJGQslJtcGqfgHpPnfftwqw
RDMLDWLNTLTTNjNgvdqbqRnwqbfwPRzbVHHV
mgdNgdTSMWmSQsQsBQcFSQJr
RqQhRpsdqnvdlPBfzdVlVJPM
SSZsDmSmssGZbJVwPBSzBBMfCf
LFFNGLgLHFWrWHFmLWrLWLrsQshqQnspNcRTjnpTtjRRjh
DshNcgmDVClpCfRs
TnZjTWrtrqtWnGTrbqqTTZZwMpSVRSflRMflMjRCSfpJMSJl
wHbGHrWHWrbnbFtTZcLzLgHzzgcmpNzzzz
hfWQdhQHmPWhqdhQqpdQqWtzvwtCMCRvNCwNzMtNsHsz
lBLnJZLlFBlZjGFbVjjlJRSMzzSszzpGpstSpvMNtN
rVZVgZVgLnjFVlVQDDfhcfmWrQdTfp
zqTrVZvDLGdMMLtcpR
bClsCmQbjFtjljllntsGjGWPdcRWhMppPcpddR
mbggmBtQtlVqVzgrzDzv
LtpnGnGNFtbGntbbQPhTlRpRTzDlcClPCl
mSZHgZMhZVmWPHccllzPzcCP
sZhWvSsBqmBSqmgMqWZjQjfjrLbvGbtNFjvLtb
TvMZMTTzWHNNFPsNbvDG
dhVmwfhcnhRnRfdlGsDNNGqNLFNNTGdq
JTcVVTlThmfmrrWQZHMrpZtJ
zGMBMzPNDNcNZLBzcmLvbHltDbWjbthhqvvHtg
rdJSQSTfQrRnsRfJJQHhWgbhtQblgHWgWH
nTrlpVfSpswsrsTSdnRsfnJJPBZmMBcBZZGmZBmBMmcCNzpC
nfzcnSlRJJScTZTzJZnsNjNrHQqrWBjsBRdWBr
LgHwDLwmMDCphttsqDjNNssBGNsGQB
hvwgwvghPbpggLtmmbCmSfzFfVSlZnncJTPZHSnF
DbsnzDCsBPHDQHFD
GGcWWnrGSjBMrMlhfr
GNpqddqWLqdScWqcVnCswmzJRVzVVbJp
NzPpPBppzjbpCrrQhggqvwwqRwrwQl
SDddnLcDLncghQBWvvgR
tfSLLBmmmDJGFDLJmMMsZZssZzPTzjTpzZzP
RRCrJbSfNrRQjvvHppmpbZvv
llhVGGGMPVTMlTdVzcPVHZmvqpvqZFhHFqmjFrHF
ccGlzPMVwBGfBrLCDJrDLf
VcVGZZVMlncjTqcjsWWf
hzJRtRphQJtBRhzFpdrfrqrFsqswWrmsTmFr
LJHzBQJRhPHpzQWBRzphHRQSMZlnbGMVMVnLMGbDvvbMVl
sVdHFFmhPGVTdFmVFsgPdBBtBZjSpGSvtpBztpGjzt
HCHwlncHfpnjSSpBzz
wWQwlWWlfWcQMfCrfwTRDrHsDmPDgFVTRVsV
qllqNlmglNNdzLDddGGNSHScMHMWPcPSqptQSSHJ
bhhbChVsRjwGRCbZCcSZPpPMMWJSPMtPpW
BhTVBsbrhCTrhfbrCTTTRRfngzrnnLvdzgGvNzdzLNvrLm
nNwNPnjzPsNRHpFDHLLsLVHF
MSBMgMZmWqScCFGWWDFGVvwW
JBghBwTrgchrTbQRjztQPQbfhQ
PPBpBHGfBHGpRRPDLMmnscRLdnzmdw
bMFVTNVTVjbbrCWCsndsDwjDzwmwsnms
QQbJrCCMWCVCVMShHGPQlHhghGlt
dBQMdJQHbWMWHZLRRsmPVJmppJqG
FSrzFnPnGNrlsGps
FvwTnCzDznTwzhtHjZvbdbjQfZgPMv
gJjVQzLgLvPJdMrsDsQtdQrw
hBpmWfSfHCWNfmSppMrDDMwwMbDMlMcbcB
fhphGpfNCpNSNRhGhqPVvjvjjjTzVRPzLr
TsnznnrZsNwGNrbWbSvVgWzVSbgv
mBBFBFQFBhSHggVnmvfW
BJFcRLFFBhLpMNcdNCscZNnqld
vqwQGZNSwNQHQQZNSwvpwMdlnMfBClZBTzBnTfTJCB
sbcrjscccmPmrtFRrtcsPssmVJBfTCldnJJdVzMlBnBJTBlR
tbDmhtdDrPjbDcrDWSHGqQqvHpWSgNHh
VVWSwCpWTVWWwVbbvPJDwvDtwtMttLtH
nfNLcNsfZNnGggZNNqGlMPPDDrlvGHHrtPJMHP
fhgqfznczcjpVRjFLSLz
pvcBCrPrcPBpTccGjrQhQdwMsqdGQddswqhS
FggLnnFzzNFNmstlShMVwQtsgq
RnbzHmNfRHmmnLzRnLDRZHRrCPJBvCWWpcjvJpwWfjwvrc
HfdzzrGfRrQqrGVnznQvgjcjhhlMTlFjchFMVL
swwWWBPNwPwZbvPMFTLjTlgP
BJBJJDZtSrJqnFFfFJ
lqqMSMBMttLMjtHjqjrdBnSfcpfwCTGbCffwCcwbSfTcJf
gVFhVRZgVzJshFZVTbbFfvpcwCTCfbcG
hRWZzRVVZmsWJVRQsQmqqndQrnqnQLqnQqtBlr
SgPhCGGzczlCDVDWrlTL
jvdvFvjqwfdrNfNDlzLzRW
jzjFHnvdtdnmHZttqmbFdFqFsSBJspcgcSPQpsQPBPgpgmSG
qqmQFmrbbWWrtqTVVrgLJTzzNzrJ
nCjMGncHMJvzmmHmVV
DpjPDGwnmDhbwQqZtqqW
JlTTLLMRqlMlJMJgBLLnnCZCFrrrdTGrjPjGFr
vwVpHVHVwvHmQVsFFPZQrjrrrZPNdn
wtvmtwvpmbwVvssPflSBlRBqLMlLJBzSLb
rtrTtBwTsfjZrnqJQplNTcqqlvQT
sHzdWFzSzmGDDRVGVDGHWVhvcLLpNpqJCQqLhClhlcvqpC
VRbmRmRHGdsnggbPMMftZB
LMhtCSSftfTzdCdMhSCdMsQGQbGnbGQQMQggDNgR
FjFHWJwJjRNvQggwnDsm
plBVRRqWRHVHWFTdTthTLCfzflzh
VjVdrHFWPmTjRGSRGq
DMWMZDncQDcfpQzmTQTSQRGTGqNz
WMnsCZJCffDnfCfvnZCPhwVrHBVrBlVHrhswLh
TCZltglCZWQsMhqRHhsrHC
vbbNBbGBmNLzczNmNjrRVbhqHMsVqwHVRwqH
mzBSmzDLvPDPzcLPvGzWWSnsJstWlSsSlddWZJ
nlFJZTlBbFBVZldFnlZlCQvQrsMQzzsCdCLszvLD
hPwgVqSwmRcgSRmWgSwmsfrLPssLvQQfDPDvfMfD
htSwtWHWVRNtWmwgtnJplnbFpBbNTnBTFN
vnhBfSSvRttPJnlctl
frHVDHFwfDLVzVlJMNTHllJHMNlZ
bGGFFbqVLVVbzrFwGfdgFdwvhpCqmBpRqWpBpQpSSpSQSm
RMBMMZBBmmmhZmPjTZhZRPnNQvwWfcSvDfQWBSfdQSNdDc
LHzlVGHqVGzHGzsbCbqglbJddCcvJNDDvdDCJSQvWfwf
HlzrHHgsqbHsVGHqbsGsbbsqFmmjnTTFmnjmRQRPFTFPZtrj
LSLWRMLrLHqqwCBJqCstsG
vbQfPjndQnbcQfmndRwttBNZRsGdsCBJ
bmcnTfbvvPRRRFcmfhjHgzMrSrSMSLzSWgVhML
cqWNtsdsWdlsnBsDJwZJSzFFBZ
RhfvggPfffbVbfPmpMvRRFrZDFFbzDDZZrHwJDbwzb
QhRgvpTVpPgJVGTWWNcTtqNLtG
nppPsSPtPZtFdSWdvFvSnnPscRjjHRTLLjCmRLTmCCscrRcc
wwGqDqfMrGqlhllqhhNwzGNTjCRTmRLTHzJjzBmmRmjCLc
qrblfrVwGwbhwqghfqVhNMhtWSvFdPdQtQdgtWpvWPQWQv
cLJvcccHNcLDwCdRDvjdDR
ttPChbqhZmtWGCtZQwBdsQPQdwwsddQF
WnqbbgGVZCZnnlWhCVtbtVgMMrJLLJNrNcHMJNJTJNMp
vLvWghFhBWqGsVTV
JdpdmbrBmsQGGlVqdw
CJZMHPMZJHmzCnZHHrMjSvcDLDccNSBCDDFDjj
mDgnmRVmqgCSScsVllCj
HLTTMTHZQjZzTzprTGPwtcdlLcllWllWtCSwld
QMHHPzNrQBQGNHzQqbjnBbBbmbfjbqjb
tgPNgzzsSPhjSgbPztSbpDJZRJDTRLTTpRHpNRHZ
crlfGGFlBGBrBcrnFlrFFFCrLpHHJTcLRJJVJvDHtHZRDDRR
tFFtrdmGffnndmzhbWPgzPdsWQPW
JHhvgvzJhBGSLHhgBBSBHzdBflDfllTqLlwLqflfMcctCcfl
RjWQWrnjpjjdNQmmNNWZWpCZtqtDtMwwwcwtcDqcTDqC
PpNPjQspmWpPWRWnVQQpQsWVvvggJBvBSGGdJVhJSJBFdb
FrPTcrCGbcTCChrwNMRDMRvWRdHvzVRVTR
LJmQSmQfJnssmjsHSRFHSHzdVzSFHV
nQtgssgfstjLnmplttgFLLPPpGBrcrchBhCbhhqwPPCC
qFtZtFzstvvPvqttNrCJFWJRFCJFRRWR
ffBBfjQdmdQBfQfmLVQRPRpNNCgPNNRThdWPrr
fQVQlHnBQjBLjlvDqsvPqHMsctSb
rqhJnTTJqTchnTdhncmmgMVqtSBsBspgBtHLLWsBBWpWBHSH
bPldNljGZjNCbFCbwwGDWtBDDtsDtLwt
NjvlvvzQFFQhQqdQnMTM
DJHGghhFhHgsGgThrtrQWBPPJWWCzzzP
lTpffNTdZfrcwlCwCrWz
dmvdvffSSpjTLjFhFMRRbnRbjj
LfSqfmvfWPBPdljNNFVFzVJLNjJz
QZQnQcpMhwhZchQnwbvCCDNDCNpzpFsJpsRsRj
rchgQnvHHhQgvnwHGTffdmdTddTGfWHW
SzZGtmTjgzQCpJwpVqrVzz
NWddPllPDvdbccgcHJLCpClFLLVpFLLVLV
bbdRRWDNdPfgfWPWhdccNddRmBQTSGTTTZnmBQZjmsmnhGst
LgvFffmfVFczCWWmWCSh
MbwbTBDwbZtwBDMhSCGhscWSwVCsSw
QMtdQbqtbZTjVbMtZDMgffnFnJpFvrvFprgvgq
pztdqqzCrpvFqpJQwCvWBRGRWLWcWNBsNNQcNR
HdbjSbVhfhcRscRmNm
MDPffbjbjgFgzCZdFdgt
BmDQZbmmfbmbvhvhbgCsCl
GqVqMHwpGTLHLzwqJlCgsgShhvGvJgGS
LTpzpLFprpfmNrBBlfQP
RjRhBqZbwBbjcwgjPmRtZjZfWFfFznWQNVzQFQQnFzWmMN
vpTPDCdpPSpTSSMzNHzMvFQNNWNM
PDCpLGlGPdrlqRqbqbBhRLqR
PmHZWmJzzzppHfHdHfddDMDLhRbMRgRMNNnPgNMM
TCwBCSSjwqwVqQldTSQTtjVhtbbhbgLLbLLbMggMbDRttc
QBrwFlqCfdzHdvzF
GvgGvgfvlzlHGQWRjGMpjZLjZpGW
DVsqJtnDsJTsTqjpLTdcmWWLpTMp
NNqVhsPrrhqnJNnJNzgBvvjHCCPSjCvQQQ
pqnswpqrrtqrnMsMPMqzVfgGzHBVGVftfBGzGG
QWFQhhmDhJDmJJhhJLcTcfHVvTlTFTfVvgzG
ZDZLddWWSgDCggChRSMPspMjpnqjMPjj
MGwMFLFfssfffcGcDrnCllZtnHQCnDCZWD
dbTvTThtvVVVNWVHClWQzzlQ
TjbgBqTBvBvjRvbqvRmPGMcwSPJPfstSsfMBMf
VtCjjqgwvhCCQdSPJJdGnwwLTT
brrBsmNWlzBpSDcpSWLcWD
SSFsrrrBrCqHVVQFjj
LQQNLgvNDnNPHPDQjtGjnmjttBjVhSmJ
sbWfsMFwdCpdCdwWJVVSltVJlLSlLSft
TFcdMTbpdbwdwgTDQLgDNNrTNz
gfgSsnmnWnhhctcJ
ljjMfwwRTNbRqNlzVzjbtDvPvchvPCccChtJtPVW
GjwpwMpbjMbRMNwqzwpQgQQBfdHfSFrBmQBg
FmcmmTTMdPTGHjtGGnctcN
DgqzTqCgDgpZTrqhSbSpzZfpnHjHlnbtbHBGnGjtQHnlNGWt
zppLhfZTfDqsLMPdMVRwwM
RtsMZJSFRWbRsJbFnFzVBpBqgdRdGzGBpDDj
cTmvrlMQLHLllrhwlmfdQqBpdVpDqGdVpjVzBq
wvTfcHhhmHlhTNLFCnFnNnFnFnMFZJ
grjsjJhhNscgJFgPBnbHwLsRHzHfRLbH
ldMMSSvqtSMGmSSMqLRnlRwbrLlRLRRWwL
VtvDdTGGGCvMDMDTvdjhQjZppPNrJVpZPVFg
wctlscwwBTDnJcLNLHDN
bhhMnhqjzFRjjjPdNDDSvLdJ
MWzMzbrZZZmWQzhWbMhwlspstmnswswllBCgpG
rzmddBcmgFjRzSHHDR
vqpgbnGpqwgbpHtbtRjHTjTfFH
WWqCwvCqCJvCJvwpqvMvnvJMdPgZQQdZcWhBBBrPlLlmdQdm
ZdHTtNPNPSRBbFjjTTsr
WmDhGggmgWWJcZmMhVllzjJCrbjFzbsFFRCj
MMGDmMGGgDGgnWGWpNnvSHStLnwffZtHnw
ddZqRdqjvjZdndlfjwZQQCzmqcHLzzTTHTHzchHTmT
BPVPBBWVLbFFrWgJLpNHcPSHCPSCSCChcCPHTH
VFNbBJrGGJVZGGLwQGnjQL
NllFnzNNnNnNzmrHmDFGLGcccRGjGwHChGwwGh
StMZgPdBgbbBLLvCwCvgGwwj
PsfPtBJMtPZMJPbZVVPPMMDnjDlNlmrnmWnmqzpqmVFm
mGGCppgGWWgmGBzMVzBBBbBS
HnrRdvZvTMtSBtbZ
rHwRrjlrRwrnJrCsCDlLWCqcmCMM
zHhDNmDMNNJHfMNJzjsdvvsvbvjGdCGW
tVwttwwVVFBSFSZqSLjsqLdLCWCvGWcdLs
ZwZgwgpBFGlHgNQmGM
TNqhqvqFNWFrlqFqtDTrhTSTbLfjmjzbwMmMbjzLPDwGLPPP
scVRRQHVQVVHcRHpVgJJCRHMMZGMzCwwLZPZGMMCzLGwZw
dHsnQdHHdnBHspJRsVppFlNTSGGNBWBtTShNTFvG
hdZthMghfbbHCgQgBp
mLjTTjWrTrSCbZsLSbCS
VVPJrjqcWVmrjcmWRWTZTPcWldMNqvhnhMFdvdMhfNdldGNM
sFlsgtZFLFZzSZzpnQrJ
DjRbcjRdBrpRQpMJMJ
jNcfDqqfcDBbmqDFggpFCTpgCNhWWG
LMGGbbpLcpVVbfcpcpdvPVQPmZzJZjqSjSjgZgzqZgzTmm
BrRnBWrtRlhBjmqZCnqJgCSM
FDWWrBHHBBDHhFHttrWFttNpfLppbfcGGsfcGsFfccpcMd
jzHqjHLVqQQlHfzqlbbzqHQscvNsVrvnNZTtvNvvvcrGtv
gJCSRwRpJRtNNSTstnTT
wCMnFgnpCMPnJgpDQbqdQdQQLbzqDHfH
MpqJWmqlNNHmmwwBLLvL
QzFDFfdfQTtSGzTDVMdSFQDwHLBhHLjHjbTbHvLggccwHb
VQfsSDfGftfsdGSDSSQSFssZJCCMlMWWZPWPJMZlRp
lcqqhSsgTMgcqBBZnqZTBJJpdGpGVdRNMJHNGjRJdd
VbfCmPbtttfwwWHdGGrjHPdrRrHN
CffFFmwmDWmtCtvQbSVnTlBSDsqZhVBBSc
gPZTgmwvcnqPzhnW
GJVbDhpjsbWzjfNNNNMj
DFCbrBJsFJpBhbVFJCtvTgmtRTtQQltmwm
BLZgTJPqZzFgCGgCFlFF
ljfcDvNDtHcftNdMCQnCRnhnGjCChG
mVvSdDNDHlmHfNVlSWcSDmtpbpTzppwLPPLPPJLwTwBLPS
FHRzMqvQHvndJnFlNdhZ
fcjWWsjsSmmrgsGgjGcGWsPsnhZddffRdTtNDnZlnDnDThhT
WSPcPsGPSRGCmLcGgpHCzBVqzbQBVpqwwQ
PJzwjrVHzLPrZJHgSsNWbNbmNQtnLSSs
hGhqpTBRRGFFpMpBqGpSNlQQmWlntDbmTQSsml
MpcvMqBRhpFRNCcjwZwPZwJfwjHz
QWJsVCQDbVWbprrWSZWFcmrS
wMwvjRftMLhHfjhdMhRhjtMZrmrmZqBSpBSprvSpTzBTSF
dLNNjhhhVDlNDspN
MNmmtzlQPQmlttlQlHBGFFsHsPnGnFGWgs
CwhhwVZcRVRcCRDWLDFHWWFGss
hwdwdCwCZVSwZcrvhVwCJtbtQtpzmzQHvtpzQmmmpp
CccMdVLJcnCVhCfmjGjlfwwwMwWG
HDSbggDTNbRDHtTgrDpwmnGFfpGgfWfBFmlm
HbDzvQNzHbQLnQddZCcn
jWlqRjWwsqjHHqRDDPMPgpMLpgSMnggC
VQvFfFbdTcfhbcvCpvPrnZgLLpSgLp
PNQVbNTTcbdbfQdbmdVVGfbhBJlHWqGljJqBlqJJlsJJwqqR
WFGnWBTrvtgnjBWsFWggTPlhSfmRSRhZMcSfhZZpRmtZ
CdswHJHNsCbHLVVcZclphwcchfphZZ
LdDCLHsHzbNNNQDsJLNGgPPBvFzjggPrPTrrFB
pGFwwLTPjDcSCPpSdsqtMRMDdVQdVVQz
JBJjZgWgJHvHJgJJbBhNJvgZzsQVRqzdfQQQMMBszRzRzRfV
nlNZWZlJngbvNjgZhNvHhJvprcTclFCcTPSlTCcSpFcLrG
PdHJVCbSJmSVHdLdHbsbsqRwnlDWhZnZccWqDwqDVw
NvMFlGrQTvgpggFNwZhwWWhhqRWRhTqz
gMjvtMpNMrfFrvlffgmdjLLjCmmLHBddLJBS
zNrlzhJGdlHGHplCJQQVbLhRFRbccDSbVDLqRb
WwmwnWjvjmjZPPFFFRDZqVbqqJBS
tmjMJstnWnjvnsTnQMfrQMldrGlCrGfl
MqWfZlpjMPBgffgPNNQnVnnqRsNVLVmR
TcwGCTSvthpzCCTNVnsQVSnRnRQnNn
TbrpDvvCvCwTGDzvzhpzDzljHBZbHWZgHPZJZjJJHfPf
DWNNQQHRpsRWDQPQqHqqgJBCsjjsFFFngBzgjJzl
tMhMwTrTDLMdmMLtMMrbmVbZhJJnnFCCjnlJjjjjBzFBgZ
ttTtDmbfqWcWfqPp
QhvTQqggFsmvjsFTmqZrzzwZrHnwpnplpZ
WCJVGCSLtDPPtHDbHDbdpnrMnMrrpwlZrwpznLpl
VVJbbVfStVHJJVtGmvsfjvssFFTvvsQj
pBCqCqhWjpnWCnffJDjfWzJBZdcvwcPdvJvJcgcrdGdvggrv
tlhbHbmNTbQgbGRvbZGrcg
tVFLQNVlmTmQLQhpzMCBzCpzjjFMnz
qhWHwNqLHrLJjqgHddFchMdnnGnRhMcR
pTzTPVfZQPffNVtVVZfptRGsRbbbbcDsMMZsMZMdRn
CfzPVzCfPBzPBqvWqgBwjNLjjS`;

const data = input.split("\n");

//Part One

const mappedData = data.map((item) => {
  const s1 = item.substring(0, item.length / 2);
  const s2 = item.substring(item.length / 2);
  return [s1, s2];
});
console.log(mappedData);

const result = mappedData.reduce((acc, item) => {
  const [partOne, partTwo] = item;
  const [sharedItem] = partOne
    .split("")
    .filter((item) => partTwo.includes(item));
  if (sharedItem === sharedItem.toUpperCase()) {
    acc += sharedItem.charCodeAt() - 38; // A has priority 27 and its ascii code is 65 so we subtract 38
  } else {
    // It's lowecase
    acc += sharedItem.charCodeAt() - 96; // a has a priority of 1 and its ascii code is 97 so we subtract 96
  }
  return acc;
}, 0);

console.log(result);

//Part Two
const secondData = input.match(/(?:.+\n?){3}/g);
const secondMappedData = secondData.reduce((acc, item) => {
  const [elfOne, elfTwo, elfThree] = item.split("\n");

  const allItems = [elfOne.split(""), elfTwo.split(""), elfThree.split("")];
  const [sharedItem] = allItems.reduce((p, c) =>
    p.filter((e) => c.includes(e))
  );

  if (sharedItem === sharedItem.toUpperCase()) {
    acc += sharedItem.charCodeAt() - 38;
  } else {
    acc += sharedItem.charCodeAt() - 96;
  }
  return acc;
}, 0);

console.log(secondMappedData);
